<?xml version="1.0" encoding="UTF-8"?>
<project default="jar">
	<property name="javahome" value="/Library/Java/JavaVirtualMachines/jdk-17.0.10.jdk/Contents/Home" />	
	<property name="javac" value="${javahome}/bin/javac" />
	<property name="java" value="${javahome}/bin/java" />

	<target name="compile" description="Build all imageio source folders into combined output folder">
		<mkdir dir="output/classes" />
		<javac destdir="output/classes" debug="on" verbose="off" fork="true" executable="${javac}">
			<src path="common/common-image/src/main/java" />
			<src path="common/common-io/src/main/java" />
			<src path="common/common-lang/src/main/java" />
			<src path="imageio/imageio-batik/src/main/java" />
			<src path="imageio/imageio-bmp/src/main/java" />
			<src path="imageio/imageio-clippath/src/main/java" />
			<src path="imageio/imageio-core/src/main/java" />
			<src path="imageio/imageio-dds/src/main/java" />
			<src path="imageio/imageio-hdr/src/main/java" />
			<src path="imageio/imageio-icns/src/main/java" />
			<src path="imageio/imageio-iff/src/main/java" />
			<src path="imageio/imageio-jpeg/src/main/java" />
			<!-- src path="imageio/imageio-jpeg-jai-interop/src/main/java" / -->
			<!-- src path="imageio/imageio-jpeg-jep262-interop/src/main/java" / -->
			<src path="imageio/imageio-metadata/src/main/java" />
			<src path="imageio/imageio-pcx/src/main/java" />
			<!-- src path="imageio/imageio-pdf/src/main/java" / -->
			<src path="imageio/imageio-pict/src/main/java" />
			<src path="imageio/imageio-pnm/src/main/java" />
			<src path="imageio/imageio-psd/src/main/java" />
			<!-- src path="imageio/imageio-reference/src/main/java" / -->
			<src path="imageio/imageio-sgi/src/main/java" />
			<src path="imageio/imageio-tga/src/main/java" />
			<src path="imageio/imageio-thumbsdb/src/main/java" />
			<src path="imageio/imageio-tiff/src/main/java" />
			<!-- src path="imageio/imageio-tiff-jai-interop/src/main/java" / -->
			<!-- src path="imageio/imageio-tiff-jdk-interop/src/main/java" / -->
			<src path="imageio/imageio-webp/src/main/java" />
			<src path="imageio/imageio-xwd/src/main/java" />
			<classpath path="lib/batik-all-1.18.jar"/>
			<classpath path="lib/xml-apis-ext-1.3.04.jar"/>
		</javac>
	</target>
	
	<target name="jar" depends="compile" description="Build twelvemonkeys-all.jar">
		<jar destfile="output/twelvemonkeys-all.jar">
			<fileset dir="output/classes" />
			<metainf dir="lib/META-INF" />
		</jar>
	</target>
	
	<target name="clean" description="Remove all generated artificats in the output directory">
		<delete dir="output"/>
	</target>
</project>
